import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from '@/providers';
import LanguageSwitch from '@/components/language-switch';
import { getDictionary, Locale } from './dictionaries';
import LocaleProvider from '@/providers/locale-provider';
import { ModeToggle } from '@/components/mode-toggle';
import { PalletteDropdown } from '@/components/pallette-dropdown';
import { getServerPalette } from '@/lib/get-server-pallette';
import Link from 'next/link';
import { LocalizedLink } from '@/components/localized-link';
import { buttonVariants } from '@/components/ui/button';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'pl' }, { lang: 'en' }];
}

export default async function RootLayout({ children, params }: LayoutProps<'/[lang]'>) {
  const { lang } = await params;

  const dict = await getDictionary(lang as Locale);
  const pallette = await getServerPalette();

  return (
    <html
      lang={lang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${pallette}`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <LocaleProvider translations={dict} locale={lang as Locale}>
          <Providers>
            <div>
              <LanguageSwitch lang={lang as Locale} />
              <ModeToggle />
              <PalletteDropdown />
              <LocalizedLink href="/register" className={buttonVariants({ variant: 'link' })}>
                Register
              </LocalizedLink>
            </div>
            {children}
          </Providers>
        </LocaleProvider>
      </body>
    </html>
  );
}
